# Generated by Django 3.2.11 on 2022-01-17 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Two wheeler', 'two_wheeler'), ('Four wheeler', 'four_wheeler')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(10)])),
                ('date_of_registration', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
