# Generated by Django 3.2.11 on 2022-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_of_registration',
            field=models.CharField(max_length=8),
        ),
    ]
