# Generated by Django 3.2.11 on 2022-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_vehicle_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_of_registration',
            field=models.DateField(help_text='dd-mm-yyyy'),
        ),
    ]
