# Generated by Django 3.2.11 on 2022-01-26 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_vehicle_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_of_registration',
            field=models.DateField(help_text='yyyy-mm-dd | mm-dd-yyyy'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(help_text='TN 07 AL 2406 - TEN DIGIT', max_length=15, unique=True),
        ),
    ]
