# Generated by Django 3.2.11 on 2022-03-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
