# Generated by Django 3.2.11 on 2022-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220309_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
