# Generated by Django 3.2.11 on 2022-03-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_vehicle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.CharField(blank=True, default='trimble', max_length=30, null=True),
        ),
    ]
